version: "3.9"

services:
  api:
    build: .
    container_name: fastapi_api
    restart: unless-stopped
    network_mode: host

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    network_mode: host
    environment:
      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      WEBHOOK_URL: http://localhost:5678/
      N8N_EDITOR_BASE_URL: http://localhost:5678/
      GENERIC_TIMEZONE: Europe/Moscow
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - api
      - playwright-mcp

  playwright-mcp:
    image: mcr.microsoft.com/playwright/mcp
    container_name: playwright-mcp
    entrypoint: ["node", "cli.js"]
    command: ["--headless", "--browser", "chromium", "--no-sandbox", "--port", "8931"]
    restart: unless-stopped
    network_mode: host

volumes:
  n8n_data:
